export type Variety="Moscato"|"Chardonnay"|"Merlot"|"Cabernet Sauvignon"|"Tannat"|"Riesling"|"Outras";
export type Family="Espumante"|"Branco"|"Tinto"|"Suco";
export type Producer={id:string;name:string;city:string;region:"Serra Gaúcha"|"Campanha Gaúcha";score:number};
export type Block={id:string;producerId:string;variety:Variety;hectares:number;method:"Manual"|"Mecanizada"};
export type Receipt={id:string;unit:"TU"|"AD";producerId:string;blockId:string;variety:Variety;kg:number;hour:number;brix:number;acidity:number;kind:"received"|"forecast";status:"Processado"|"Em análise"|"A caminho";lab:"Aprovado"|"Pendente"|"Revisão";docs:boolean;glt:"Vinculada"|"Pendente"|"N/A";family:Family;lotId:string|null};
export type Analysis={id:string;receiptId:string;brix:number;acidity:number;ph:number;status:Receipt["lab"];minutes:number};
export type Lot={id:string;receiptId:string;variety:Variety;family:Family;producerId:string;tankId:string|null;liters:number;complete:boolean;stage:string;future:string};
export type Tank={id:string;unit:"TU"|"AD";family:Family;varieties:Variety[];capacity:number;volume:number;reserved:number;product:string;status:string;temp:number|null;min:number;max:number;releaseHour:number|null;cipHours:number};
export type Order={id:string;lotId:string;operation:string;resource:string;hour:number;status:string};
export type SafraDB={reference:string;plans:Record<Variety,number>;producers:Producer[];blocks:Block[];receipts:Receipt[];analyses:Analysis[];lots:Lot[];tanks:Tank[];orders:Order[];units:{id:"TU"|"AD";name:string;city:string;dockTons3h:number}[]};

export const varieties:Variety[]=["Moscato","Chardonnay","Merlot","Cabernet Sauvignon","Tannat","Riesling","Outras"];
export const familyOf:Record<Variety,Family>={Moscato:"Espumante",Chardonnay:"Espumante",Merlot:"Tinto","Cabernet Sauvignon":"Tinto",Tannat:"Tinto",Riesling:"Espumante",Outras:"Branco"};
export const yieldOf:Record<Variety,number>={Moscato:.70,Chardonnay:.72,Merlot:.68,"Cabernet Sauvignon":.67,Tannat:.66,Riesling:.71,Outras:.69};
const plans:Record<Variety,number>={Moscato:10_200_000,Chardonnay:8_400_000,Merlot:9_100_000,"Cabernet Sauvignon":5_200_000,Tannat:4_100_000,Riesling:2_400_000,Outras:3_600_000};
const received:Record<Variety,number>={Moscato:7_800_000,Chardonnay:6_100_000,Merlot:5_400_000,"Cabernet Sauvignon":3_000_000,Tannat:2_500_000,Riesling:1_100_000,Outras:1_500_000};
const cityRows=[["Bento Gonçalves","Serra Gaúcha"],["Garibaldi","Serra Gaúcha"],["Flores da Cunha","Serra Gaúcha"],["Monte Belo do Sul","Serra Gaúcha"],["Farroupilha","Serra Gaúcha"],["Santana do Livramento","Campanha Gaúcha"]] as const;

function producers(){return Array.from({length:312},(_,i)=>{const [city,region]=cityRows[i%cityRows.length];return{id:`PR-${String(i+1).padStart(4,"0")}`,name:i===311?"Azienda Domenico":`Produtor parceiro ${String(i+1).padStart(4,"0")}`,city,region,score:88+i%13};});}
function blocks(ps:Producer[]){const out:Block[]=[];ps.forEach((p,i)=>{for(let j=0;j<(i%2===0?2:1);j++)out.push({id:`TL-${String(i+1).padStart(4,"0")}-${j+1}`,producerId:p.id,variety:varieties[(i+j*3)%7],hectares:1.8+((i*7+j*11)%73)/10,method:p.region==="Campanha Gaúcha"?"Mecanizada":"Manual"});});return out;}

const special:Receipt[]=[
 {id:"REC-26180",unit:"TU",producerId:"PR-0147",blockId:"TL-0147-1",variety:"Moscato",kg:18_420,hour:-4.2,brix:18.9,acidity:6.4,kind:"received",status:"Processado",lab:"Aprovado",docs:true,glt:"N/A",family:"Espumante",lotId:"SG-260218-038"},
 {id:"REC-26184",unit:"TU",producerId:"PR-0082",blockId:"TL-0082-1",variety:"Chardonnay",kg:19_200,hour:-.7,brix:18.7,acidity:7.1,kind:"received",status:"Em análise",lab:"Pendente",docs:true,glt:"N/A",family:"Espumante",lotId:"SG-260218-044"},
 {id:"REC-25972",unit:"AD",producerId:"PR-0312",blockId:"TL-0312-1",variety:"Tannat",kg:24_880,hour:-25,brix:20.8,acidity:6.1,kind:"received",status:"Processado",lab:"Aprovado",docs:true,glt:"Vinculada",family:"Tinto",lotId:"CG-260217-012"},
 {id:"REC-25997",unit:"TU",producerId:"PR-0211",blockId:"TL-0211-1",variety:"Merlot",kg:21_100,hour:-19,brix:20.1,acidity:6.6,kind:"received",status:"Processado",lab:"Aprovado",docs:true,glt:"N/A",family:"Tinto",lotId:"SG-260217-097"}
];

function historic(bs:Block[]){const out=[...special];let seq=1;for(const [vi,v] of varieties.entries()){let left=received[v]-special.filter(x=>x.variety===v).reduce((s,x)=>s+x.kg,0);while(left>0){const kg=Math.min(left,18_200+(seq*947+vi*613)%6_700);const pi=(seq*17+vi*31)%300;const producerId=`PR-${String(pi+1).padStart(4,"0")}`;const b=bs.find(x=>x.producerId===producerId)??bs[pi];const unit=pi%11===0?"AD":"TU";out.push({id:`REC-H-${String(seq).padStart(4,"0")}`,unit,producerId,blockId:b.id,variety:v,kg,hour:-(8+(seq*13)%1_050),brix:17.8+((seq*7+vi*3)%35)/10,acidity:5.4+(seq*11%25)/10,kind:"received",status:"Processado",lab:seq%47===0?"Revisão":"Aprovado",docs:seq%53!==0,glt:unit==="AD"?(seq%19===0?"Pendente":"Vinculada"):"N/A",family:familyOf[v],lotId:`${unit==="AD"?"CG":"SG"}-26H-${String(seq).padStart(4,"0")}`} as Receipt);left-=kg;seq++;}}return out;}
function forecast(bs:Block[]){const counts:Record<Variety,number>={Moscato:14,Chardonnay:22,Merlot:8,"Cabernet Sauvignon":6,Tannat:5,Riesling:5,Outras:4};const out:Receipt[]=[];let seq=0;for(const [vi,v] of varieties.entries()){for(let i=0;i<counts[v];i++){const pi=(seq*23+vi*37+81)%312;const producerId=`PR-${String(pi+1).padStart(4,"0")}`;const b=bs.find(x=>x.producerId===producerId)??bs[pi];const unit=pi>298||pi%13===0?"AD":"TU";out.push({id:`REC-F-${String(seq+1).padStart(3,"0")}`,unit,producerId,blockId:b.id,variety:v,kg:18_600+(seq*1_113+vi*407)%6_300,hour:1.1+(i*5+vi*3)%68+(i%3)*.35,brix:18.1+((seq*5+vi)%29)/10,acidity:5.7+(seq*9%21)/10,kind:"forecast",status:"A caminho",lab:"Pendente",docs:seq%17!==0,glt:unit==="AD"?(seq%9===0?"Pendente":"Vinculada"):"N/A",family:familyOf[v],lotId:null});seq++;}}return out.sort((a,b)=>a.hour-b.hour);}

const keyTanks:Tank[]=[
 {id:"AU-118",unit:"TU",family:"Espumante",varieties:["Moscato"],capacity:120_000,volume:98_700,reserved:15_000,product:"Base espumante · Moscato",status:"Fermentação",temp:15.8,min:14.5,max:17,releaseHour:76,cipHours:4},
 {id:"AU-074",unit:"TU",family:"Espumante",varieties:["Chardonnay"],capacity:120_000,volume:112_300,reserved:0,product:"Base espumante · Chardonnay",status:"Transferir",temp:16.1,min:14.5,max:17,releaseHour:54,cipHours:4},
 {id:"VI-203",unit:"TU",family:"Tinto",varieties:["Merlot"],capacity:112_000,volume:76_400,reserved:24_000,product:"Merlot",status:"Fermentação",temp:24.2,min:22,max:26,releaseHour:70,cipHours:5},
 {id:"VI-219",unit:"TU",family:"Tinto",varieties:["Cabernet Sauvignon"],capacity:112_000,volume:61_800,reserved:34_000,product:"Cabernet Sauvignon",status:"Estável",temp:23.7,min:22,max:26,releaseHour:40,cipHours:5},
 {id:"SU-042",unit:"TU",family:"Suco",varieties:["Outras"],capacity:96_000,volume:84_100,reserved:5_000,product:"Suco integral",status:"Resfriamento",temp:4.1,min:2,max:6,releaseHour:66,cipHours:5},
 {id:"AU-121",unit:"TU",family:"Espumante",varieties:["Moscato","Chardonnay","Riesling"],capacity:110_000,volume:0,reserved:0,product:"Disponível",status:"Higienizado",temp:null,min:14.5,max:17,releaseHour:null,cipHours:0},
 {id:"AU-133",unit:"TU",family:"Espumante",varieties:["Riesling"],capacity:120_000,volume:91_600,reserved:18_000,product:"Base espumante · Riesling",status:"Fermentação",temp:15.6,min:14.5,max:17,releaseHour:62,cipHours:4},
 {id:"VI-188",unit:"AD",family:"Tinto",varieties:["Tannat"],capacity:114_000,volume:103_900,reserved:0,product:"Tannat",status:"Atenção",temp:27.1,min:22,max:26,releaseHour:58,cipHours:5},
 {id:"AU-126",unit:"TU",family:"Espumante",varieties:["Moscato","Chardonnay"],capacity:140_000,volume:65_000,reserved:54_000,product:"Corte base",status:"Estável",temp:15.4,min:14.5,max:17,releaseHour:52,cipHours:4},
 {id:"AU-140",unit:"TU",family:"Espumante",varieties:["Moscato","Chardonnay"],capacity:160_000,volume:110_000,reserved:36_000,product:"Base espumante",status:"Fermentação",temp:16.4,min:14.5,max:17,releaseHour:80,cipHours:4},
 {id:"BR-052",unit:"TU",family:"Branco",varieties:["Outras","Chardonnay"],capacity:150_000,volume:126_000,reserved:10_000,product:"Vinho branco",status:"Estável",temp:13.9,min:11,max:15,releaseHour:32,cipHours:4},
 {id:"BR-061",unit:"TU",family:"Branco",varieties:["Outras","Riesling"],capacity:180_000,volume:165_000,reserved:5_000,product:"Vinho branco",status:"Fermentação",temp:14.2,min:11,max:15,releaseHour:88,cipHours:4}
];
function tanks(){const generated=Array.from({length:38},(_,i)=>{const capacity=[140_000,160_000,180_000,200_000][i%4];const family=["Espumante","Tinto","Branco","Tinto"][i%4] as Family;const volume=Math.round(capacity*(.72+(i*7%17)/100)/100)*100;const raw=capacity*.95-volume;const reserved=Math.max(0,Math.round(raw*(.72+(i%3)*.08)/100)*100);const prefix=family==="Espumante"?"AU":family==="Tinto"?"VI":"BR";const base=family==="Tinto"?24:family==="Espumante"?15.8:13.5;return{id:`${prefix}-${300+i}`,unit:i%9===0?"AD":"TU",family,varieties:varieties.filter(v=>familyOf[v]===family),capacity,volume,reserved,product:`${family} · lote em processo`,status:i%11===0?"Estável":"Fermentação",temp:base+((i%5)-2)*.25,min:family==="Tinto"?22:family==="Espumante"?14.5:11,max:family==="Tinto"?26:family==="Espumante"?17:15,releaseHour:55+(i*11)%64,cipHours:family==="Tinto"?5:4} as Tank;});return[...keyTanks,...generated];}
function lots(rs:Receipt[],ts:Tank[]){return rs.filter(r=>r.kind==="received"&&r.lotId).map((r,i)=>{const overrides:Record<string,string|null>={"SG-260218-038":"AU-118","SG-260218-044":null,"CG-260217-012":"VI-188","SG-260217-097":"VI-203"};const candidates=ts.filter(t=>t.family===r.family);const tankId=Object.prototype.hasOwnProperty.call(overrides,r.lotId!)?overrides[r.lotId!]:candidates[i%candidates.length]?.id??null;return{id:r.lotId!,receiptId:r.id,variety:r.variety,family:r.family,producerId:r.producerId,tankId,liters:Math.round(r.kg*yieldOf[r.variety]),complete:tankId!==null&&i%37!==0&&r.docs,stage:tankId?(i%4===0?"Clarificação":"Fermentação"):"Aguardando destinação",future:r.family==="Espumante"?"Corte de espumante · lote a definir":`${r.family} · lote de envase a definir`} as Lot;});}

function createDB():SafraDB{const ps=producers(),bs=blocks(ps),rs=[...historic(bs),...forecast(bs)],ts=tanks(),ls=lots(rs,ts);const analyses=rs.filter(r=>r.kind==="received").map((r,i)=>({id:`LAB-${String(i+1).padStart(5,"0")}`,receiptId:r.id,brix:r.brix,acidity:r.acidity,ph:3.05+(i*3%42)/100,status:r.lab,minutes:r.lab==="Pendente"?42:18+i%24}));const orders=ls.slice(0,96).map((l,i)=>({id:`OP-26-${String(i+1).padStart(4,"0")}`,lotId:l.id,operation:i%3===0?"Prensagem":i%3===1?"Transferência":"Clarificação",resource:i%3===0?`P-0${i%4+1}`:l.tankId??"Sem recurso",hour:-6+i%84,status:l.tankId?(i%5===0?"Em execução":"Planejada"):"Bloqueada"}));return{reference:"2026-02-18T13:00:00-03:00",plans,producers:ps,blocks:bs,receipts:rs,analyses,lots:ls,tanks:ts,orders,units:[{id:"TU",name:"Tuiuty",city:"Bento Gonçalves · RS",dockTons3h:118},{id:"AD",name:"Azienda Domenico",city:"Santana do Livramento · RS",dockTons3h:82}]};}
export const safraDb=createDB();
